# site settings
title: Stephen Hung 
subtitle: Software Engineer and Student
email: hung.stephen.yh@gmail.com
description: A Portfolio, Resume, and Blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://stphnhng.github.io/" # the base hostname & protocol for your site
author: Stephen Hung
street_address:
city: Bay Area
state: CA
zip_code: 
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/stphnhng
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/stphnhung/
linkedin_url: https://www.linkedin.com/in/stephen-hung
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
